import React, { useState } from "react";
import Head from "next/head";

interface WheelProps {
    
}

const Wheel: React.FC<WheelProps> = () => {
    const [entries, setEntries] = useState<string[]>([]);
    return (<div>WHEEL GOES HERE</div>)
}

const WheelInputForm: React.FC = () => {
    const handleAction = (e: Event) => {
        e.preventDefault();
        console.log("handleAction");
    }

    const handleAddField = (e: Event) => {
        e.preventDefault();
        console.log("handleAddField");
        }
    
    const handleDelField = (e: Event) => {
    e.preventDefault();
    console.log("handleDel");
        }


    const handleChange = (e: Event) => {
    console.log(e.target.value)
        }

    return (<div>
        <h2>WHEEL INPUT FORM GOES HERE</h2>
        <form>
        <button onClick={(e) =>handleDelField(e)}> REMOVE FIELD</button>
        <input type="text" onChange={(e) => handleChange(e)} />
        <button onClick={(e) =>handleAddField(e)}> NEW FIELD</button>
        <button onClick={(e) =>handleAction(e)}> CLICK ME</button>
        </form>
    </div>)
}


export default function Home() {
    return (
        <>
            <Head>
            <title>Lucky Wheel</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>HI CHAT</h1>
                <WheelInputForm />
                <Wheel />
            </main>
        </>
    );
}
