import Head from "next/head";
import Wheel from "../components/Wheel";
import WheelForm from "../components/WheelForm";



export default function Home() {
    return (
        <>
            <Head>
            <title>Lucky Wheel</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>HI CHAT</h1>
                <WheelForm />
                <Wheel />
            </main>
        </>
    );
}
