import {useState} from "react";
import Head from "next/head";
import Wheel from "../components/Wheel";
import WheelForm from "../components/WheelForm";



export default function Home() {
    const [values, setValues] = useState<string[]>([]);
    const updateValues = (values: string[]) => {
        setValues(values);
    }

    return (
        <>
            <Head>
            <title>Lucky Wheel</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>HI CHAT</h1>
                <WheelForm callback={updateValues}/>
                <Wheel values={values}/>
            </main>
        </>
    );
}
